jardinapi:
  build: .
  links:
    - mosquitto
  volumes:
    - .:/src/web
  ports:
    - "8080:8080"
  environment:
    - MQTT_HOST=mosquitto

mosquitto:
  image: ansi/mosquitto
  ports:
    - "1883:1883"
