version: "3"

services:

  api:
    build: ./serveur-web/api-v2/
    network_mode: "host"
    depends_on:
      - mqtt

  mqtt:
    image: toke/mosquitto
    ports:
      - 9001:9001
      - 1883:1883

