version: 2.1

orbs:
  python: circleci/python@0.3.0

jobs:
  backend-test:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout

      - run: pip install paho-mqtt flask flask-api flask-cors

      - run:
          name: Setup database
          working_directory: serveur-web/api-v2/database
          command: python migration.py

      - run:
          name: Run tests
          working_directory: serveur-web/api-v2
          command:  python app_tests.py

  backend-lint:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout

      - run: pip install autopep8

      - run:
          name: Fail if lint changes files
          working_directory: serveur-web/api-v2
          command: |
            DIFF=$( find **/*.py -exec autopep8 --global-config pyproject.toml --diff {} \; )
            if [ -z $DIFF ]; then echo "Code is fine."; else echo "Lint errors detected. please run format.sh" && exit 1; fi;

workflows:
  main:
    jobs:
      - backend-test
      - backend-lint
