version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    working_directory: ~/project

    docker:
      - image: circleci/python:3.7

    steps:
      - checkout

      - run: sudo pip install pipenv
      - run: pipenv install
      - run: pip install paho-mqtt flask flask-api flask-cors

      - run:
          name: Run Bash scripts
          working_directory: serveur-web/api-v2
          command: |
            pwd
            ls
            bash ./setup.sh
            bash ./run.sh

workflows:
  main:
    jobs:
      - build
